Repository jupyter-incubator/sparkmagic, pull requests merged in 2023-09, with the labels that each got.

#835 Add support for application/json mime type in statement output
  CHANGELOG.md
  sparkmagic/sparkmagic/livyclientlib/command.py
  sparkmagic/sparkmagic/tests/test_command.py
  sparkmagic/sparkmagic/utils/constants.py
Labels: kind:enhancement

#836 Fix formatting issue
  sparkmagic/sparkmagic/livyclientlib/command.py
  sparkmagic/sparkmagic/tests/test_command.py
Labels: kind:bug

#831 Fix for notebook version 7+
  sparkmagic/requirements.txt
  sparkmagic/sparkmagic/serverextension/handlers.py
Labels: kind:bug

#837 fix: run CI on pull_request to run on forks
  .github/workflows/docker_build.yml
  .github/workflows/tests.yml
Labels: kind:enhancement, please code review
