Repository jupyter-incubator/sparkmagic, pull requests merged in 2024-11, with the labels that each got.

#935 feat(docs): update for newer versions Jupyter notebook
  CHANGELOG.md
  Dockerfile.jupyter
  README.md
Labels: kind:documentation, size:M

#936 chore(ci): drop official support for Python 3.7, add support for 3.12
  .github/workflows/tests.yml
  CHANGELOG.md
  sparkmagic/sparkmagic/tests/test_sparkkernelbase.py
Labels: size:M

#937 release: 0.22.0
  CHANGELOG.md
Labels: please code review, size:S

#941 publish wheels
  .github/workflows/publish.yml
Labels: size:S, lgtm
